version: '3.4'

services:
  postgres:
    ports:
      - '5432:5432'
    restart: always
    container_name: quickorderdb-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quickorderdb
    volumes:
      - 'quickorderdb-postgresql-volume:/var/lib/postgresql/data'
    image: 'postgres:10.4'
    networks:
      - quickorderdb-network
  mongodb:
    image: mongo:latest
    container_name: quickorderdb-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: quickorderdb
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: mongod --auth
    volumes:
      - 'quickorderdb-mongodb-volume:/data/db'
    networks:
      - quickorderdb-network
  quickorder.adapters.driving.api:
    image: ${DOCKER_REGISTRY-}quickorderadaptersdrivingapi
    build:
      context: .
      dockerfile: Adapters/Driving/Api/Dockerfile
    ports:
      - '8090:80'
    depends_on:
      - 'postgres'
      - 'mongodb'
    networks:
      - quickorderdb-network  
volumes:
  quickorderdb-postgresql-volume:
  quickorderdb-mongodb-volume:

networks:
  quickorderdb-network:
    driver: bridge